<?php
$lang = array (
'version'		=> 'VinaGet v2.7.0 Final',
'homepage'		=> 'vinaget.us',
'title'			=> '%s - Premium link generator',
'login'			=> 'Please enter password to login.',
'password'		=> 'Password',
'plugins'		=> 'Plugins',
'premium'		=> 'Premium Accounts :',
'moreacc'		=> 'More accounts >>>',
'lessacc'		=> '<<< Less accounts',
'main'			=> 'Main Window',
'donate'		=> 'Donate Acc',
'listfile'		=> 'Server Files',
'admin'			=> 'Admin Panel',
'check'			=> 'Check Acc',
'log'			=> 'Log Out',
'welcome'		=> '<font color="#FF3300"><b><font color="#FFFF66">%s</font> - Fast and unlimited premium link generator</b></font>',
'update'		=> '<br><font color="#dbac58"><b>There\'s an update for vng270</b> - <a href="https://code.google.com/p/vinaget-script/source/list">Get Revision %s</a></font>',
'maxline'		=> '(max 10 link for one times)',
'example'		=> '<span style="font-familty: Arial; color: #FFFFFF; font-size: 10px">Example: http://www.megaupload.com/?d=ABCDEXYZ<font size="3">|</font>password</span>',
'sbdown'		=> 'Download',
'dlhere'		=> 'Download here:',

// donate 
'donations'		=> '<font color="#FF3300">We are also in need of donations! If you can we would appreciate your offerings.<br/>Donate your Account !</font>',
'acctype'		=> 'Account Type:',
'sbdonate'		=> 'Donate Account',
'invalid'		=> '<img src="images/error.png"> <font color="red"><b>Invalid account. Please re-check your data!</b></font>',
'success'		=> '<font color="#FF3300">Thanks for donating your account. Your account has been created successfully our database.</font>',
'dsuccess'		=> '<img src="images/success.png"><br/><b><font color="#86a5d5">Donate Success!</font></b>',
'getloading'	=> '<img src="images/loading.gif"><br/>checking...',
'notaccess'		=> 'You do not have permission to access this page !',

//check

//notice
'notice'		=> '<blink><font color="#cbac57">Auto del file after <b>%s</b>. Limit <b>%s</b> file per <b>%s</b> for <b>1</b> IP</font></blink><br/>',
'yourjobs'		=> 'Your IP: %s. Your jobs: %s (max: %s).You used %s (max: %s).<br/>',
'status'		=> 'File size limit: %s. Total jobs: %s (max: %s). Server load: %s (max allowed: %s). Users online: %s',

//time 

'ago'			=> 'ago',
'days'			=> 'days',
'hours'			=> 'hours',
'mins'			=> 'mins',
'sec'			=> 'sec',


//down
'errorget'		=> 'Failed to generate the link. Please try again !',
'errordl'		=> 'Your link has been generated by another ip address !',
'erroracc'		=> '<font color="red">Account/Cookie Error !!!</font>',
'svload'		=> 'Server load is too high.',
'issex'			=> '<b><font color=red>is this link sex ??? ==&#9658;</font> <a href=http://www.google.com/search?q=%s><font color=#00CC00>%s</font></a><br/><font color=#FFCC00>if not ==&#9658; Repost:</font> <font color=#0066CC>%s</font><font color=#FF3300>|</font><font color=#ff9999 face=Arial>not3x</font></b><br/>',
'errorlink'		=> '==&#9658; Invalid link !',
'manyjob'		=> 'Too many download jobs.',
'countMBIP'		=> '<center><b><i><font color=red>You only can download %s per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitPERIP'	=> '<center><b><i><font color=red>You only can download %s file per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitip'		=> 'Too many download jobs for this ip.',
'notdl'			=> 'Can not get file size.',
'cantjob'		=> '<center><b><i><font color=red>Can not create new job</font></i></b></center>',
'filebig'		=> '<center><b><font color=#00CC00>%s</font> <font color=red>%s ==&#9658; File too big ! </font><font color=#3399FF>when allowed only</font> <font color=#FFCC00>%s</font></b></center>',

//Server Files
'notfound'		=> 'Not Found!',
'del'			=> 'Delete',
'rname'			=> 'Rename',
'notfile'		=> 'No Files Found',
'acdis'			=> 'Action Disabled',
'ac'			=> 'Action',
'name'			=> 'Name',
'size'			=> 'Size',
'date'			=> 'Date',
'original'		=> 'Original Link',
'clickcheck'	=> 'Click here to check link',
'total'			=> 'Total',
'used'			=> 'You used',
'reset'			=> 'Reset per',
'canl'			=> 'Cancel',
'deld'			=> 'Deleted!',
'nname'			=> 'New Name',
'bname'			=> 'You can\'t rename file to blank name!',
'rnameto'		=> 'renamed to',

//report
'unavailable'	=> 'Service Unavailable',
'disabletrial'	=> 'your link is temporary disable for trial account.',
'adult'			=> 'Adult Video Detected',
'ytb_captcha'	=> 'Captcha Found. Please run on different server',
'ytb_Error'		=> 'Error Locating Downlod URL',
'reportpass'	=> '<CENTER>The file you are trying to download is password protected. Please enter the password below.</CENTER>',
'outofbw'		=> '<font color=red>Account out of bandwidth !!!</font>',

//new
'accpremium'	=> 'Premium Account',
'direct'		=> 'Direct Link',
'checkall'		=> 'Check All',
'uncheckall'	=> 'Un-Check All',
'invert'		=> 'Invert Selection',
'error1'		=> '<b><font color=red> %1$s </font></b>',
'error2'		=> '<b><a href="%2$s" style="text-decoration:none"><font color="red" face="Arial" size="2"><s>%2$s</s></font></a> <img src=images/chk_error.png width="15" alt="errorlink"> <font color=#ffcc33 face=Arial size=2>==&#9658; %1$s</font></b>',
'pluginerror'	=> '%1$s plugin was error. Contact admin!</font>',
'noaccount'		=> 'There\'s no %1$s account in database. Contact admin!</font>',
'cantconnect'	=> 'Our server can\'t connect to %1$s',
'accfree'		=> 'Our %1$s account is FREE',
'accinvalid'	=> 'Our %1$s account invalid',
'blockCountry'	=> 'Our Country has been banned by %1$s',
'blockIP'		=> 'Our IP has been banned by %1$s',
'blockAcc'		=> 'Our %1$s account has been blocked',
'LimitAcc'		=> 'Our %1$s account has reach bandwidth limit',
'dead'			=> 'Link Dead !!!',
'again'			=> 'please try again',
'notwork'		=> 'Not Work',
'work'			=> 'Work',
'removed'		=> '[REMOVED]',
'unknown'		=> 'unknown',
'notsupport'	=> 'Sorry. We do not support your link !',
'notsupportacc'	=> 'Not support account, use cookie instead',
'notsupportpass'=> 'Not support password currently for %1$s',
'checkacc'		=> 'Check %1$s account',
'noplugin'		=> 'You don\'t have %s account checker.<br/>Ask someone to make it'

);
/*
* Open Source Project
* Vinaget by ..::[H]::..
* Version: 2.7.0 Final
* English Language
* Language Class By [FZ]
*/
?>