<?php
$config = array();
$config['secure'] = true;
$config['password'] = "demo, pass, test";
$config['admin'] = "demo";
$config['homepage'] = "vinaget.us";
$config['download_prefix'] = "vinaget_";
$config['limitMBIP'] = 100 * 1024;
$config['ttl'] = 6 * 60;
$config['limitPERIP'] = 10;
$config['ttl_ip'] = 1;
$config['max_jobs_per_ip'] = 100;
$config['max_jobs'] = 500;
$config['max_load'] = 50;
$config['max_size_default'] = 2048;
$config['title'] = "[color=blue] download [/color]";
$config['colorfilename'] = "green";
$config['colorfilesize'] = "red";
$config['ziplink'] = true;
$config['apiadf'] = "http://api.adf.ly/api.php?key=94793cf6c45d36ed3d008d098fcfb964&uid=343503&advert_type=int&domain=adf.ly&url=";
$config['listfile'] = true;
$config['showdirect'] = false;
$config['longurl'] = true;
$config['privatefile'] = false;
$config['privateip'] = false;
$config['checkacc'] = true;
$config['checklinksex'] = false;
$config['rename'] = true;
$config['delete'] = true;
$config['proxy'] = "";
$config['badword'] = "porn";
$config['language'] = "english";
?>