<?php
$config = array();
$config['secure'] = true;
$config['password'] = "user1, user2, user3, user4";
$config['admin'] = "admin";
$config['homepage'] = "vinaget.us";
$config['download_prefix'] = "vinaget_";
$config['download_suffix'] = "_vinaget";
$config['limitMBIP'] = 100 * 1024;
$config['ttl'] = 6 * 60;
$config['limitPERIP'] = 10;
$config['ttl_ip'] = 1;
$config['max_jobs_per_ip'] = 100;
$config['max_jobs'] = 500;
$config['max_load'] = 50;
$config['max_size_default'] = 2048;
$config['title'] = "[color=blue] download [/color]";
$config['colorfilename'] = "green";
$config['colorfilesize'] = "red";
$config['listfile'] = true;
$config['showdirect'] = true;
$config['longurl'] = true;
$config['privatefile'] = false;
$config['privateip'] = false;
$config['checkacc'] = true;
$config['checklinksex'] = false;
$config['rename'] = true;
$config['delete'] = true;
$config['display_error'] = false;
$config['ziplink'] = false;
$config['apiadf'] = "http://api.adf.ly/api.php?key=94793cf6c45d36ed3d008d098fcfb964&uid=343503&advert_type=int&domain=adf.ly&url="; //http://adfoc.us/api/?key=31d0604803eec636ed3ffac5a1364c6e&url=
$config['apirutgon'] = "http://bc.vc/api.php?key=10bf5c6f0db2a00780a91aaa18745a14&uid=37018&url=";
$config['Googlzip'] = false;
$config['googleapikey'] = 'AIzaSyBzbeSDQoOYKUDLr1v5FOuZRtKwnqEOXxM';
$config['bitly'] = false;	
$config['BitLylogin'] = 'giaythuytinh176';
$config['BitLyApi'] = 'R_9a6d99b3b945b803be01c176d61b9298';
$config['badword'] = "porn, sex, hentai, xxx, jav";
$config['language'] = "english";
$config['skin'] = "default";
?>