<?php
/*
* Home page: http://vinaget.us
* Blog:	http://blog.vinaget.us
* Script Name: Vinaget 
* Version: 2.6.3
* Description: 
	- Vinaget is script generator premium link that allows you to download files instantly and at the best of your Internet speed.
	- Vinaget is your personal proxy host protecting your real IP to download files hosted on hosters like RapidShare, megaupload, hotfile...
	- You can now download files with full resume support from filehosts using download managers like IDM etc
	- Vinaget is a Free Open Source, supported by a growing community.
* Code LeechViet by VinhNhaTrang
* Developed by ..:: [H] ::..

*/


$lang = array (
//main
'version'		=> 'VinaGet v2.6.3 Final',
'homepage'		=> 'vinaget.us',
'title'		=> '%s - Premium link generator',
'login'		=> 'Please enter password to login.',
'password'		=> 'Password',
'plugins'		=> 'Plugins',
'premium'		=> 'Premium Accounts :',
'moreacc'		=> 'More accounts >>>',
'lessacc'		=> '<<< Less accounts',
'main'		=> 'Main Window',
'donate'		=> 'Donate Acc',
'listfile'		=> 'Server Files',
'check'		=> 'Check Acc',
'log'		=> 'Log Out',
'welcome'		=> '<font color=#FF3300><B><font color=#FFFF66>%s</font> - Fast and unlimited premium link generator</B></font>',
'maxline'		=> '(max 10 link for one times)',
'example'		=> '<SPAN style="FONT-FAMILY: Arial; COLOR: #FFFFFF; FONT-SIZE: 10px">Example: http://www.megaupload.com/?d=ABCDEXYZ<font size=3>|</font>password</SPAN>',
'sbdown'		=> 'Download',
'dlhere'		=> 'Download here:',

// donate 
'donations'		=> '<font color=#FF3300>We are also in need of donations! If you can we would appreciate your offerings.<br/>Donate your Account !</font>',
'acctype'		=> 'Account Type:',
'sbdonate'		=> 'Donate Account',
'invalid'		=> '<img src="images/error.png"> <font color=red><b>Invalid account. Please re-check your data!</b></font>',
'success'		=> '<font color=#FF3300>Thanks for donating your account. Your account has been created successfully our database.</font>',
'dsuccess'		=> '<img src="images/success.png"><BR><b><font color=#86a5d5>Donate Success!</font></b>',
'getloading'		=> '<img src="images/loading.gif"><BR>checking...',
'notaccess'		=> 'You do not have permission to access this page !',

//check

//notice
'notice'		=> '<blink><font color=#cbac57>Auto del file after <B>%s</B>. Limit <B>%s</B> file per <B>%s</B> for <B>1</B> IP</font></blink><BR>',
'yourjobs'		=> 'Your IP: %s. Your jobs: %s (max: %s).You used %s (max: %s).<BR>',
'status'		=> 'File size limit: %s. Total jobs: %s (max: %s). Server load: %s (max allowed: %s). Users online: %s',

//time 

'ago'		=> 'ago',
'days'		=> 'days',
'hours'		=> 'hours',
'mins'		=> 'mins',
'sec'		=> 'sec',


//down
'errorget'		=> 'Failed to generate the link. Please try again !',
'errordl'		=> 'Your link has been generated by another ip address !',
'erroracc'		=> '<font color=red>Account/Cookie Error !!!</font>',
'svload'		=> 'Server load is too high.',
'issex'		=> '<B><font color=red>is this link sex ??? ==&#9658;</font> <a href=http://www.google.com/search?q=%s><font color=#00CC00>%s</font></a><br/><font color=#FFCC00>if not ==&#9658; Repost:</font> <font color=#0066CC>%s</font><font color=#FF3300>|</font><font color=#ff9999 face=Arial>not3x</font></b><BR>',
'errorlink'		=> '==&#9658; Invalid link !',
'manyjob'		=> 'Too many download jobs.',
'countMBIP'		=> '<center><b><i><font color=red>You only can download %s per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitPERIP'		=> '<center><b><i><font color=red>You only can download %s file per %s ! Please wait <font color=green size=4>%s</font></font></i></b></center>',
'limitip'		=> 'Too many download jobs for this ip.',
'notsupport'		=> '<b><a href=%s style=\'TEXT-DECORATION: none\'><font color=red face=Arial size=2>%s</font></a>  <font color=#ffcc33 face=Arial size=2>==&#9658; Sorry. We do not support your link !</font></b><BR>',
'notdl'		=> '<b><a id=\'notsupport\' href=%s style=\'TEXT-DECORATION: none\'><font color=#ffcc33 face=Arial size=2>%s</font></a></b> <font color=red> ==&#9658; Can not get file size.</font><BR>',
'cantjob'		=> '<center><b><i><font color=red>Can not create new job</font></i></b></center>',
'filebig'		=> '<center><b><font color=#00CC00>%s</font> <font color=red>%s ==&#9658; File too big ! </font><font color=#3399FF>when allowed only</font> <font color=#FFCC00>%s</font></b></center>',

//Server Files
'notfound'		=> 'Not Found!',
'del'		=> 'Delete',
'rname'		=> 'Rename',
'notfile'		=> 'No Files Found',
'acdis'		=> 'Action Disabled',
'ac'		=> 'Action',
'name'		=> 'Name',
'size'		=> 'Size',
'date'		=> 'Date',
'original'		=> 'Original Link',
'clickcheck'		=> 'Click here to check link',
'total'		=> 'Total',
'used'		=> 'You used',
'reset'		=> 'Reset per',
'canl'		=> 'Cancel',
'deld'		=> 'Deleted!',
'nname'		=> 'New Name',
'bname'		=> 'You can\'t rename file to blank name!',
'rnameto'		=> 'renamed to',

//report
'dead'		=> '==&#9658; Link Dead !!!',
'again'		=> '==&#9658; please try again',
'notwork'		=> '==&#9658; Acc not work',
'unavailable'		=> 'Service Unavailable',
'disabletrial'		=> 'your link is temporary disable for trial account.',
'adult'		=> 'Adult Video Detected',
'ytb_captcha'		=> 'Captcha Found. Please run on different server',
'ytb_Error'		=> 'Error Locating Downlod URL',
'reportpass'		=> '<CENTER>The file you are trying to download is password protected. Please enter the password below.</CENTER>',
'outofbw'		=> '<font color=red>Account out of bandwidth !!!</font>',

);
?>